### PR TITLE
Fix book examples

### PR DESCRIPTION
**Pull request by ilslv**
## Synopsis

Windows doesn't handle path starting with `/`.

## Solution

Remove `/` prefix and add `Windows` and `macOS` targets for `test-book` CI job. 

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
Issue is definitely on `skeptic` side of things: https://github.com/budziq/rust-skeptic/issues/131

**Comment by ilslv** [comment]
@tyranron yeah, already working on it. Looks like something wrong with parsing on windows, because ubuntu and macOS rustc commands contain link to the crates.io dependency: `"async_trait=/home/runner/work/skeptic-mre/skeptic-mre/book/tests/target/debug/deps/libasync_trait-9a7703a13941d9d0.so"`, while windows lacks it.

**Comment by ilslv** [comment]
Waiting for merge of https://github.com/budziq/rust-skeptic/pull/132

**Comment by ilslv** [comment]
## FCM

```
Fix book examples on Windows (#202, #200)
```

**Review by tyranron — APPROVED** [review]
@ilslv perfect! thanks! 🍻

**Pull request merged**
