### PR TITLE
Fix missing feature and scenario headers

### PR DESCRIPTION
**Pull request by Daanoz**
Another fix for the terminal log prints when color is on. Should relate to #299 (and maybe #282).

If I understand the principle, each step is first printed in white and after the step is done, the white line is replaced by either green or red text, depending on the outcome. However, during feature and scenario start the `lines_to_clear` is also incremented. When the first the step of a scenario completes it replaces those 3 lines (feature start, scenario start, step start) with 1 line being the green/red step complete. I could not find a use-case where it made sense to replace these lines as well.

### CODE REVIEW

**Review by tyranron — APPROVED** [review]
@Daanoz sorry for the long delay, and thank you for the fix! 🍻

**Comment by Daanoz** [comment]
No problem, any idea when this as part of 0.21 would be available?

**Comment by tyranron** [comment]
@Daanoz after merging #302. In a week or so.

**Comment by tyranron** [comment]
@Daanoz sorry for being late. Released as [0.20.1](https://crates.io/crates/cucumber/0.20.1).

**Pull request merged**
