### PR TITLE
Implement `writer::Tee`

### PR DESCRIPTION
**Pull request by ilslv**
## Synopsis

For now `cucumber` can't output to multiple terminating `Writer`s: `Basic`, `JUnit` or `Json`. 

## Solution

Implement `writer::Tee`

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by tyranron** [comment]
Let's name it `writer::Tee`. It's more wide-known terminology/slang for such naming following the [`tee` utility](https://man7.org/linux/man-pages/man1/tee.1.html).

**Comment by ilslv** [comment]
## FCM

```
Implement `writer::Tee` (#160)
```

**Review by tyranron — CHANGES_REQUESTED** [review]
Discussed in a talk to:
1. Make `ArbitraryDiscard` and `FailureDiscard` wrappers for packing `Writer`s which doesn't implement `ArbitraryWriter` and `FailureWriter` into `writer::Tee`, while making `writer::Tee` always calling both `left` and `right`.
2. Move `W` type parameter of `writer::Ext` to methods.

**Review by tyranron — APPROVED** [review]

**Comment by tyranron** [comment]
@ilslv thanks!

**Pull request merged**
