### PR TITLE
Implement writer::JUnit (#50)

### LINKED ISSUE #50: Feature: xunit/junit output
I believe that adding j/xunit output support would go a long way to streamlining the tests, as those are the formats supported by IDE's and CI tools, so it would make cucumber-rust fit in like a glove with how devs work right now, rather than relying on reading the text output.

I will probably give it a whack myself, as it's of high interest to me, but certainly, welcome any pointers and suggestions!

### PR DESCRIPTION
**Pull request by ilslv**
Resolves #50 

## Synopsis

For now `cucumber` output can't be parsed by default `CI` tools.

## Solution

Implement `writer::JUnit`

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [ ] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
Security-audit will be failing until https://github.com/chronotope/chrono/pull/578 is resolved

**Comment by tyranron** [comment]
@ilslv [`junit-report` 0.7](https://docs.rs/junit-report/0.7.0) is out, so we can finish this.

**Comment by ilslv** [comment]
## FCM

```
Implement writer::JUnit (#147, #50)
```

**Review by tyranron — APPROVED** [review]
@ilslv mentioning in Book and in README was missing 😕

**Pull request merged**
