### PR TITLE
Support Cucumber Expressions (#124)

### PR DESCRIPTION
**Pull request by ilslv**
Part of #124

## Synopsis

Sometimes `regex` is a bit too much and we want something easier. [Cucumber expressions](https://github.com/cucumber/cucumber-expressions) are a great fit in this scenario. 

## Solution

Support in attribute macros with `#[given(expr = "...")]`/`#[given(expression = "...")]`

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by ilslv** [comment]
Current blockers:

- `derive_more` release with https://github.com/JelteF/derive_more/pull/175 fix to make CI happy
- `Cucumber Expressions` language has no formal specification. Because of this the no way for us to say that [`cucumber-expressions`][1] implementation is correct, as there is no notion of `correctness`: https://github.com/cucumber/cucumber-expressions/issues/41



[1]: https://github.com/cucumber/cucumber-expressions/issues/41

**Comment by tyranron** [comment]
@ilslv [`cucumber-expressions 0.1.0`](https://crates.io/crates/cucumber-expressions/0.1.0) is released, we can move on here.

**Comment by ilslv** [comment]
## FCM

```
Support Cucumber Expressions (#157, #124)
```

**Review by tyranron — CHANGES_REQUESTED** [review]
@ilslv we need a clear example of how to use custom parameters in Cucumber Expressions.

**Comment by ilslv** [comment]
@tyranron 

For custom parameters I propose something like this

```rust
```

**Comment by ilslv** [comment]
@tyranron for custom parameters I propose something like this 

```rust
enum Animal {
    Cat,
    Dog,
    Ferris,
}

impl FromStr for Animal {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "cat" => Ok(Self::Cat),
            "dog" => Ok(Self::Dog),
            "🦀" => Ok(Self::Ferris),
            _ => Err("expected 'cat', 'dog' or '🦀'"),
        }
    }
}

impl CustomParameter for Animal {
    const NAME = "animal";
    const REGEX = "cat|dog|🦀";
}

#[then(expr = "the {animal} is not hungry")]
async fn cat_is_fed(world: &mut AnimalWorld, animal: Animal) {
    sleep(Duration::from_secs(2)).await;

    match animal {
        Animal::Cat => assert!(!world.cat.hungry),
        Animal::Dog => assert!(!world.dog.hungry),
        Animal::Ferris => assert!(!world.ferris.hungry),
    };
}
```

With that we can validate that parameter name is right with const assertion. And to validate regex we can even use clippy lint : [Playground].
Also, as we have exact type, we can use deref-based specialisation to fallback on default parameter name in our const assertion. 


[Playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=340b1d45f2ef7638da6d7c3be4729006

**Comment by tyranron** [comment]
@ilslv let's move this discussion to the issue, because it won't be a part of this PR. And merge this PR only with `FromStr`.

**Review by tyranron — APPROVED** [review]

**Pull request merged**
